# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "rtsx_usb_sdmmc"
    "lz4"
    "lz4_hc"
  ];
  boot.kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest-x86_64-v3;
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.zswap = {
    enable = true;
    # And optionally configure further:
    maxPoolPercent = 40;
    shrinkerEnabled = true;
    compressor = "zstd";
    acceptThresholdPercent = 90;
  };

  boot.initrd.systemd = {
    enable = true;
    services.rollback = {
      description = "Rollback Btrfs root và quản lý dữ liệu lưu trữ 30 ngày";

      # KÍCH HOẠT SYSTEMD DEVICE HOOK: Trói buộc dịch vụ chạy ngay khi thiết bị sda3 xuất hiện
      wantedBy = [ "initrd.target" ];

      # Mẹo cốt lõi: Phải dùng 4 dấu gạch chéo ngược (\\\\) thì Systemd mới dịch đúng dấu gạch ngang của sda-3
      requires = [ "dev-sda3.device" ];
      after = [ "dev-sda3.device" ];
      before = [ "sysroot.mount" ];

      unitConfig.DefaultDependencies = "no";
      serviceConfig.Type = "oneshot";

      script = ''
        mkdir -p /btrfs_tmp

        # Thao tác mount trực tiếp vào gốc ổ đĩa Btrfs qua sda3 vật lý đã sẵn sàng
        mount -t btrfs -o subvolid=5 /dev/sda3 /btrfs_tmp

        # 1. Đóng gói root cũ thành mốc ngày giờ lưu vào kho old_roots
        if [[ -e /btrfs_tmp/root ]]; then
            mkdir -p /btrfs_tmp/old_roots
            timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/root)" "+%Y-%m-%d_%H:%M:%S")
            mv /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
        fi

        # 2. Định nghĩa hàm xóa subvolume đệ quy của Btrfs
        delete_subvolume_recursively() {
            IFS=$'\n'
            for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
                delete_subvolume_recursively "/btrfs_tmp/$i"
            done
            btrfs subvolume delete "$1"
        }

        # 3. Quản lý dọn dẹp các bản lưu cũ quá 30 ngày bằng Bash nội trú
        if [[ -d /btrfs_tmp/old_roots ]]; then
            current_time=$(date +%s)
            for folder in /btrfs_tmp/old_roots/*; do
                if [[ -d "$folder" ]]; then
                    folder_time=$(stat -c %Y "$folder")
                    age=$((current_time - folder_time))
                    if (( age > 2592000 )); then
                        echo "Xóa bản sao lưu cũ quá 30 ngày: $folder"
                        delete_subvolume_recursively "$folder"
                    fi
                fi
            done
        fi

        # 4. Tạo lại subvolume 'root' trống sạch sẽ cho phiên làm việc mới
        btrfs subvolume create /btrfs_tmp/root

        # Giải phóng ổ đĩa
        umount /btrfs_tmp
        rm -rf /btrfs_tmp
      '';
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
